In [92]:
import numpy as np

In [93]:
timestamps = 10
input_size = 4
hidden_size = 8

In [94]:
inputs = np.random.random((timestamps, input_size))
inputs

array([[0.23698546, 0.4379233 , 0.47535597, 0.12789656],
       [0.15602255, 0.0664475 , 0.30425749, 0.62934152],
       [0.30263577, 0.16797915, 0.21591057, 0.25435593],
       [0.29788018, 0.15007267, 0.66842621, 0.32867039],
       [0.642584  , 0.70374887, 0.59645014, 0.53967161],
       [0.15591522, 0.67362318, 0.13149829, 0.88583854],
       [0.9845073 , 0.36689232, 0.98193478, 0.275033  ],
       [0.63644925, 0.58836758, 0.6803463 , 0.51469344],
       [0.29026742, 0.87041909, 0.71938604, 0.50684129],
       [0.83830596, 0.13727654, 0.42128529, 0.55687669]])

In [95]:
hidden_state_t = np.ones(hidden_size) * 0.001
hidden_state_t

array([0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001])

In [96]:
Wx = np.random.random((hidden_size, input_size))
Wh = np.random.random((hidden_size, hidden_size))
b = np.random.random(hidden_size)

In [97]:
print(np.shape(Wx))
print(np.shape(Wh))
print(np.shape(b))

(8, 4)
(8, 8)
(8,)


In [98]:
np.dot(Wx, inputs[0])

array([0.5138171 , 0.36746742, 0.53333489, 1.0110641 , 0.57105496,
       0.87163777, 0.77710667, 0.6397639 ])

In [99]:
c = 10
d = 20

In [100]:
total_hidden_states = []

for input_t in inputs:
    output_t = np.tanh(np.dot(Wx, input_t) + np.dot(Wh, hidden_state_t) + b)
    total_hidden_states.append(list(output_t))
    hidden_state_t = output_t

np.shape(total_hidden_states)

(10, 8)