In [35]:
import torch
import torch.nn as nn

In [36]:
train_data = "you need to know how to code"
word_set = set(train_data.split())
word_set

{'code', 'how', 'know', 'need', 'to', 'you'}

In [37]:
vocab = {token: i for i, token in enumerate(word_set)}
vocab

{'know': 0, 'you': 1, 'how': 2, 'need': 3, 'to': 4, 'code': 5}

In [38]:
vocab2 = {}
for i, token in enumerate(word_set):
    vocab2[token] = i

vocab2

{'know': 0, 'you': 1, 'how': 2, 'need': 3, 'to': 4, 'code': 5}

In [39]:
len(vocab)

6

In [40]:
embedding_layer = nn.Embedding(num_embeddings=len(vocab), embedding_dim=3)
# num_embeddings: 임베딩 할 단어의 개수
# embedding_dim: 임베딩 벡터의 차 (지정)

In [41]:
lookup_tensor = torch.tensor([vocab["code"]], dtype=torch.long)
lookup_tensor

tensor([5])

In [42]:
w = embedding_layer(lookup_tensor)
w

tensor([[-2.1061,  0.6634, -1.2356]], grad_fn=<EmbeddingBackward0>)

In [43]:
embedding_layer.weight

Parameter containing:
tensor([[-0.4081,  0.7664, -1.0259],
        [-0.8943,  0.5873, -0.9530],
        [ 0.2683,  0.5069,  0.5527],
        [ 0.0965, -0.9875, -1.9082],
        [-0.0070, -0.4149, -1.0174],
        [-2.1061,  0.6634, -1.2356]], requires_grad=True)

In [45]:
lookup_tensor2 = torch.tensor([vocab["you"], vocab["need"], vocab["code"]], dtype=torch.long)
w = embedding_layer(lookup_tensor2)
w

tensor([[-0.8943,  0.5873, -0.9530],
        [ 0.0965, -0.9875, -1.9082],
        [-2.1061,  0.6634, -1.2356]], grad_fn=<EmbeddingBackward0>)